import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Sans, Nunito } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Sidebar, Header, RootContainer } from "@/components/shared";

const figtreeHeading = Nunito({subsets:['latin'],variable:'--font-heading'});

const dmSans = DM_Sans({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", dmSans.variable, figtreeHeading.variable)}
    >
      <body className="min-h-full flex flex-col md:p-5">
        <div className="flex bg-white flex-col h-[calc(100vh-2rem)] rounded-[30px] overflow-hidden shadow-lg">

          <Header />

          <div className="flex flex-1 overflow-hidden">
            <Sidebar />
            <main className="flex-1 overflow-y-auto bg-white">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
